on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    paths:
      - 'installers-conda/**'
      - '.github/workflows/installers-conda.yml'
      - 'requirements/*.yml'
      - 'MANIFEST.in'
      - '**.bat'
      - '**.py'
      - '**.sh'
      - '!**.md'
      - '!installers/**'
      - '!.github/workflows/installer-win.yml'
      - '!.github/workflows/installer-macos.yml'

  release:
    types:
      - created

  push:
    tags:
      - v*pre*

  workflow_dispatch:

concurrency:
  group: installers-conda-${{ github.ref }}
  cancel-in-progress: true

name: Create conda-based installers for Windows, macOS, and Linux

env:
  IS_STANDARD_PR: ${{ github.event_name == 'pull_request' && github.event.action != 'labeled' }}
  IS_BUILD: ${{ github.event.action != 'labeled' || github.event.label.name == 'build-installer-artifacts' }}
  IS_LABELED_PR: ${{ github.event.action == 'labeled' && github.event.label.name == 'build-installer-artifacts' }}
  IS_RELEASE: ${{ github.event_name == 'release' }}
  IS_PRE: ${{ contains(fromJSON('["workflow_dispatch", "push"]'), github.event_name) || (github.event.action == 'labeled' && github.event.label.name == 'build-installer-artifacts') }}

jobs:
  build-noarch-pkgs:
    name: Build ${{ matrix.pkg }}
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'labeled'
    strategy:
      matrix:
        pkg: ["python-lsp-server", "qtconsole"]
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{ github.workspace }}/installers-conda
    env:
      DISTDIR: ${{ github.workspace }}/installers-conda/dist
      pkg: ${{ matrix.pkg }}
      artifact_name: ${{ matrix.pkg }}_${{ matrix.python-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: installers-conda/build-environment.yml
          extra-specs: python=${{ matrix.python-version }}

      - name: Build Conda Packages
        run: python build_conda_pkgs.py --build $pkg

      - name: Build Artifact
        run: tar -a -C $CONDA_PREFIX -cf $PWD/${artifact_name}.tar.bz2 conda-bld

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/installers-conda/${{ env.artifact_name }}.tar.bz2
          name: ${{ env.artifact_name }}

  build-matrix:
    name: Determine Build Matrix
    runs-on: ubuntu-latest
    if: github.event.action != 'labeled' || github.event.label.name == 'build-installer-artifacts'
    outputs:
      target_platform: ${{ steps.build-matrix.outputs.target_platform }}
      include: ${{ steps.build-matrix.outputs.include }}
      python_version: ${{ steps.build-matrix.outputs.python_version }}
    steps:
    - id: build-matrix
      run: |
        target_platform="'osx-64', 'linux-64'"
        include="\
        {'os': 'macos-11', 'target-platform': 'osx-64'},\
        {'os': 'ubuntu-latest', 'target-platform': 'linux-64'}\
        "
        python_version="'3.9'"

        if [[ $IS_STANDARD_PR == 'true' ]]; then
            target_platform=$target_platform", 'win-64'"
            include=$include",{'os': 'windows-latest', 'target-platform': 'win-64'}"
        fi

        echo "target_platform=[$target_platform]" >> $GITHUB_OUTPUT
        echo "include=[$include]" >> $GITHUB_OUTPUT
        echo "python_version=[$python_version]" >> $GITHUB_OUTPUT

  build-installers:
    name: Build installer for ${{ matrix.target-platform }} Python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    needs:
      - build-matrix
      - build-noarch-pkgs
    if: ${{ ! failure() && ! cancelled() }}
    strategy:
      matrix:
        target-platform: ${{fromJson(needs.build-matrix.outputs.target_platform)}}
        python-version: ${{fromJson(needs.build-matrix.outputs.python_version)}}
        include: ${{fromJson(needs.build-matrix.outputs.include)}}
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{ github.workspace }}/installers-conda
    env:
      DISTDIR: ${{ github.workspace }}/installers-conda/dist
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_INSTALLER_CERTIFICATE: ${{ secrets.MACOS_INSTALLER_CERTIFICATE }}
      APPLICATION_PWD: ${{ secrets.APPLICATION_PWD }}
      CONSTRUCTOR_TARGET_PLATFORM: ${{ matrix.target-platform }}
      BNP_STATUS: ${{ needs.build-noarch-pkgs.result }}
      MAT_STATUS: ${{ needs.build-matrix.result }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pcregrep
        if: runner.os == 'macOS'
        run: |
          if [[ -z "$(which pcregrep)" ]]; then
              brew install pcre
          else
              echo "$(which pcregrep) already installed."
          fi

      - name: Setup Build Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: installers-conda/build-environment.yml
          extra-specs: python=${{ matrix.python-version }}

      - name: Env Variables
        run: |
          ARTIFACTS_PATH=$RUNNER_TEMP/artifacts
          CONDA_BLD_PATH=$RUNNER_TEMP/conda-bld

          echo "ARTIFACTS_PATH=$ARTIFACTS_PATH" >> $GITHUB_ENV
          echo "CONDA_BLD_PATH=$CONDA_BLD_PATH" >> $GITHUB_ENV

          [[ -d $ARTIFACTS_PATH ]] || mkdir $ARTIFACTS_PATH
          [[ -d $CONDA_BLD_PATH ]] || mkdir $CONDA_BLD_PATH

          env

      - name: Download Local Conda Packages
        if: env.IS_STANDARD_PR
        uses: actions/download-artifact@v3
        with:
          path: ${{ env.ARTIFACTS_PATH }}

      - name: Create Local Conda Channel
        run: |
          files=($(find $ARTIFACTS_PATH -name *.tar.bz2))
          echo ${files[@]}
          cd $(dirname $CONDA_BLD_PATH)

          [[ $RUNNER_OS == "Windows" ]] && opts=("--force-local") || opts=()
          for file in ${files[@]}; do
              tar -xf $file ${opts[@]}
          done

          mamba index $CONDA_BLD_PATH

          mamba search -c $CONDA_BLD_PATH --override-channels || true

      - name: Build ${{ matrix.target-platform }} conda packages
        run: |
          pkgs=("spyder")
          if [[ $IS_STANDARD_PR == "true" ]]; then
              pkgs+=("spyder-kernels")
          fi
          python build_conda_pkgs.py --build ${pkgs[@]}

      - name: Create Keychain
        if: runner.os == 'macOS' && (env.IS_RELEASE == 'true' || env.IS_PRE == 'true')
        run: |
          ./certkeychain.sh "${MACOS_CERTIFICATE_PWD}" "${MACOS_CERTIFICATE}" "${MACOS_INSTALLER_CERTIFICATE}"
          CNAME=$(security find-identity -p codesigning -v | pcregrep -o1 "\(([0-9A-Z]+)\)")
          echo "CNAME=$CNAME" >> $GITHUB_ENV

          _codesign=$(which codesign)
          if [[ $_codesign =~ ${CONDA_PREFIX}.* ]]; then
              # Find correct codesign
              echo "Moving $_codesign..."
              mv $_codesign ${_codesign}.bak
          fi

      - name: Build Package Installer
        run: |
          [[ -n $CNAME ]] && args=("--cert-id" "$CNAME") || args=()
          python build_installers.py ${args[@]}
          PKG_FILE=$(python build_installers.py --artifact-name)
          PKG_NAME=$(basename $PKG_FILE)
          echo "PKG_FILE=$PKG_FILE" >> $GITHUB_ENV
          echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV

      - name: Test Application Bundle
        if: runner.os == 'macOS'
        run: |
          installer -dumplog -pkg $PKG_FILE -target CurrentUserHomeDirectory 2>&1
          app_path=$HOME/Applications/Spyder.app
          if [[ -e "$app_path" ]]; then
              ls -al $app_path/Contents/MacOS
              cat $app_path/Contents/Info.plist
              echo ""
              cat $app_path/Contents/MacOS/spyder-script
              echo ""
          else
              echo "$app_path does not exist"
          fi

      - name: Notarize package installer
        if: runner.os == 'macOS' && (env.IS_RELEASE == 'true' || env.IS_PRE == 'true')
        run: ./notarize.sh -p $APPLICATION_PWD $PKG_FILE

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PKG_FILE }}
          name: ${{ env.PKG_NAME }}

      - name: Get Release
        if: github.event_name == 'release'
        id: get_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: bruceadams/get-release@v1.2.0

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.PKG_FILE }}
          asset_name: ${{ env.PKG_NAME }}
          asset_content_type: application/octet-stream

  remove_label:
    runs-on: ubuntu-latest
    if: always() && github.event.action == 'labeled' && github.event.label.name == 'build-installer-artifacts'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: build-installer-artifacts
