on:
  pull_request:
    paths:
      - 'installers-conda/**'
      - '.github/workflows/installers-conda.yml'
      - 'requirements/*.yml'
      - 'MANIFEST.in'
      - '**.bat'
      - '**.py'
      - '**.sh'
      - '!**.md'
      - '!installers/**'
      - '!.github/workflows/installer-win.yml'
      - '!.github/workflows/installer-macos.yml'

  release:
    types:
      - created

name: Create conda-based installers for Windows, macOS, and Linux

jobs:
  build-spyder-conda-pkg:
    name: Build spyder for ${{ matrix.target-platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target-platform: ["osx-64", "osx-arm64"]
        python-version: ["3.9"]
        include:
          - os: macos-11
            target-platform: "osx-64"
          - os: macos-latest
            target-platform: "osx-arm64"
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{ github.workspace }}/installers-conda
    env:
      DISTDIR: ${{ github.workspace }}/installers-conda/dist
      artifact_name: spyder_${{ matrix.target-platform }}_${{ matrix.python-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: installers-conda/build-environment.yml
          extra-specs: python=${{ matrix.python-version }}

      - name: Build Spyder Conda Package
        run: python build_conda_pkgs.py --build spyder

      - name: Build Artifact
        run: tar -a -C $CONDA_PREFIX -cf $PWD/${artifact_name}.tar.bz2 conda-bld

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/installers-conda/${{ env.artifact_name }}.tar.bz2
          name: ${{ env.artifact_name }}

  build-conda-pkgs:
    name: Build ${{ matrix.pkg }} for ${{ matrix.target-platform }}
    runs-on: ${{ matrix.os }}
    if: github.event_name != 'release'
    strategy:
      matrix:
        target-platform: ["osx-64", "osx-arm64"]
        pkg: ["spyder-kernels"]
        python-version: ["3.9"]
        include:
          - os: macos-11
            target-platform: "osx-64"
          - os: macos-latest
            target-platform: "osx-arm64"
          - os: macos-11
            target-platform: "osx-64"
            python-version: "3.9"
            pkg: "python-lsp-server"
          - os: macos-11
            target-platform: "osx-64"
            python-version: "3.9"
            pkg: "qdarkstyle"
          - os: macos-11
            target-platform: "osx-64"
            python-version: "3.9"
            pkg: "qtconsole"
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{ github.workspace }}/installers-conda
    env:
      DISTDIR: ${{ github.workspace }}/installers-conda/dist
      pkg: ${{ matrix.pkg }}
      artifact_name: ${{ matrix.pkg }}_${{ matrix.target-platform }}_${{ matrix.python-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: installers-conda/build-environment.yml
          extra-specs: python=${{ matrix.python-version }}

      - name: Build Conda Packages
        run: python build_conda_pkgs.py --build $pkg

      - name: Build Artifact
        run: tar -a -C $CONDA_PREFIX -cf $PWD/${artifact_name}.tar.bz2 conda-bld

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/installers-conda/${{ env.artifact_name }}.tar.bz2
          name: ${{ env.artifact_name }}

  build-installers:
    name: Build installer for ${{ matrix.target-platform }}
    runs-on: ${{ matrix.os }}
    needs: [build-spyder-conda-pkg, build-conda-pkgs]
    strategy:
      matrix:
        include:
          - os: macos-11
            python-version: "3.9"
            target-platform: "osx-64"
          - os: macos-latest
            python-version: "3.9"
            target-platform: "osx-arm64"
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{ github.workspace }}/installers-conda
    env:
      DISTDIR: ${{ github.workspace }}/installers-conda/dist
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_INSTALLER_CERTIFICATE: ${{ secrets.MACOS_INSTALLER_CERTIFICATE }}
      APPLICATION_PWD: ${{ secrets.APPLICATION_PWD }}
      CONSTRUCTOR_TARGET_PLATFORM: ${{ matrix.target-platform }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: installers-conda/build-environment.yml
          extra-specs: python=${{ matrix.python-version }}

      - name: Download Local Conda Packages
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/installers-conda/artifacts

      - name: Create Local Conda Channel
        run: |
          files=($(ls artifacts))
          echo $files
          for file in $files; do
              tar -C $CONDA_PREFIX -xf $file
          done

          mamba index $CONDA_PREFIX/conda-bld

          mamba search -c $CONDA_PREFIX/conda-bld --override-channels
